- hosts: all
  become: yes
  roles:
    - role: config-bazel
      bazel_version: 0.23.2
  tasks:
    - name: Build arm-openlab-test
      shell:
        cmd: |
          uname -a
          bazel version
        executable: /bin/bash
      environment: '{{ global_env }}'
