- hosts: all
  become: yes
  roles:
    - role: install-openjdk
      java_version: '8'
    - role: install-maven
      maven_version: '3.2.5'
  tasks:
    - name: Build arm-openlab-test
      shell:
        cmd: |
          set -ex
          echo $JAVE_HOME
        executable: /bin/bash
