- hosts: all
  become: yes
  roles:
    - role: config-gcc
      gcc_version: 7
  tasks:
    - name: Build arm-openlab-test
      shell:
        cmd: |
          git clone https://github.com/envoyproxy/envoy.git
          cd envoy
          git reset --hard 79c165f2d9d29e5af3f93f2baa51f1b29b2cdefe
          set -x
          echo $JAVA_HOME
          bazel version
          apt update
          apt-get update
          apt-get install -y \
             libtool \
             cmake \
             automake \
             autoconf \
             make \
             ninja-build \
             curl \
             unzip \
             virtualenv
          bazel build //source/exe:envoy-static
          sleep 86400
        executable: /bin/bash
      environment: '{{ global_env }}'
