- hosts: all
  become: yes
  roles:
    - role: config-python
      python_version: 3.7
  tasks:
    - name: Build arm-openlab-test
      shell:
        cmd: |
          python -V
          python3 -V
        executable: /bin/bash
      environment: '{{ global_env }}'
