name: Gitee sync test periodic job

on:
  push:
#   schedule:
#     # Excute at every 9:00am Beijing time
#     - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache src repos
      uses: actions/cache@v1
      id: cache
      with:
        path: /hub-mirror-action
        key: ${{ runner.os }}-hub-kunpeng1

    - name: Sync Github github/kunpengcompute to gitee/kunpengcompute
      run: |
        pwd
        sudo mkdir -p /hub-mirror-action
        cd /hub-mirror-action
        echo "test" > test.txt
