name: Gitee sync test periodic job

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Test 
      run: |
        pwd
        ls -la
        lscpu
        cat /etc/issue
        uname -a
  
